const stateDefault = {
  danhSachHinhAnhDanhGia: [
    {id: 1, src: "../img/reviews/1.jpg"},
    {id: 2, src: "../img/reviews/2.jpg"},
    {id: 3, src: "../img/reviews/3.jpg"},
    {id: 4, src: "../img/reviews/4.jpg"},
    {id: 5, src: "../img/reviews/5.jpg"},
    {id: 6, src: "../img/reviews/6.jpg"},
    {id: 7, src: "../img/reviews/7.jpg"},
    {id: 8, src: "../img/reviews/8.jpg"},
    {id: 9, src: "../img/reviews/9.jpg"},
    {id: 10, src: "../img/reviews/10.jpg"},
    {id: 11, src: "../img/reviews/11.jpg"},
    {id: 12, src: "../img/reviews/12.jpg"},
    {id: 13, src: "../img/reviews/13.jpg"},
    {id: 14, src: "../img/reviews/14.jpg"},
    {id: 15, src: "../img/reviews/15.jpg"},
    {id: 16, src: "../img/reviews/16.jpg"},
    {id: 17, src: "../img/reviews/17.jpg"},
    {id: 18, src: "../img/reviews/18.jpg"},
    {id: 19, src: "../img/reviews/19.jpg"},
    {id: 20, src: "../img/reviews/20.jpg"},
    {id: 21, src: "../img/reviews/21.jpg"},
    {id: 22, src: "../img/reviews/22.jpg"},
    {id: 23, src: "../img/reviews/23.jpg"},
    {id: 24, src: "../img/reviews/24.jpg"},
    {id: 25, src: "../img/reviews/25.jpg"},
    {id: 26, src: "../img/reviews/26.jpg"},
    {id: 27, src: "../img/reviews/27.jpg"},
    {id: 28, src: "../img/reviews/28.jpg"},
    {id: 29, src: "../img/reviews/29.jpg"},
    {id: 30, src: "../img/reviews/30.jpg"},
    {id: 31, src: "../img/reviews/31.jpg"},
    {id: 32, src: "../img/reviews/32.jpg"},
    {id: 33, src: "../img/reviews/33.jpg"},
    {id: 34, src: "../img/reviews/34.jpg"},
    {id: 35, src: "../img/reviews/35.jpg"},
    {id: 36, src: "../img/reviews/36.jpg"},
    {id: 37, src: "../img/reviews/37.jpg"},
    {id: 38, src: "../img/reviews/38.jpg"},
    {id: 39, src: "../img/reviews/39.jpg"},
  ],
  danhSachHinhAnhMentors : [
    {id: 1, src: "../img/mentors/mentors1.jpg"},
    {id: 2, src: "../img/mentors/mentors2.jpg"},
    {id: 3, src: "../img/mentors/mentors3.jpg"},
    {id: 4, src: "../img/mentors/mentors4.jpg"},
    {id: 5, src: "../img/mentors/mentors5.jpg"},
    {id: 6, src: "../img/library_imgs/1.jpg"},
    {id: 7, src: "../img/library_imgs/2.jpg"},
    {id: 8, src: "../img/library_imgs/3.jpg"},
  ],
  danhSachHinhAnhUSA : [
    {id: 1, src: "../img/usa/1.jpg"},
    {id: 2, src: "../img/usa/2.jpg"},
    {id: 3, src: "../img/usa/3.jpg"},
    {id: 4, src: "../img/usa/4.jpg"},
    {id: 5, src: "../img/usa/5.jpg"},
    {id: 6, src: "../img/usa/6.jpg"},
  ],
  danhSachHinhAnhBangCap : [
    {id: 1, src: "../img/certificate/1.jpg"},
    {id: 2, src: "../img/certificate/2.jpg"},
    {id: 3, src: "../img/certificate/3.jpg"},
    {id: 4, src: "../img/jobs/1.png"},
    {id: 5, src: "../img/jobs/2.jpg"},
    {id: 6, src: "../img/jobs/3.png"},
  ],
  danhSachHinhAnhKhoaHoc : [
    {id: 1, src: "../img/class/1.jpg"},
    {id: 2, src: "../img/class/2.jpg"},
    {id: 3, src: "../img/class/3.jpg"},
    {id: 4, src: "../img/class/4.jpg"},
    {id: 5, src: "../img/class/5.jpg"},
    {id: 6, src: "../img/class/6.jpg"},
  ]
};

export const ImageReducer = (state = stateDefault, action) => {
  switch (action.type) {
    default:
      return { ...state };
  }
};
